[package]
name = "BridgedUSDC"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../crates/sui-framework/packages/move-stdlib" }
One = { local = "../../../../crates/sui-framework/packages/one-framework" }


[addresses]
bridged_usdc = "0x0"
