[package]
name = "bls_signature"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
One = { local = "../../../../crates/sui-framework/packages/one-framework" }


[addresses]
bls_signature = "0x0"
