[package]
name="regulated_coin_example"
version="0.0.1"
edition="2024"

[dependencies]
# Starting with Sui 1.45, dependencies on system packages are no longer required.
One = { local = "../../../crates/sui-framework/packages/one-framework" }

[addresses]
regulated_coin_example="0x0"
