[package]
name = "OneSystem"
version = "0.0.1"
published-at = "0x3"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
One = { local = "../one-framework" }

[addresses]
one_system = "0x3"
