[package]
name = "Bridge"
version = "0.0.1"
published-at = "0xb"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
One = { local = "../one-framework" }
OneSystem = { local = "../one-system" }

[addresses]
bridge = "0xb"

